Repository replicatedhq/installer, pull requests merged in 2022-10, with the labels that each got.

#7 update kots install script to prompt for sudo access as optional
  go.mod
  pkg/handlers/scripts/install.sh
Labels: type::feature

#9 explicitly check if ARCH is amd64 to avoid conflict with arm64
  pkg/handlers/scripts/install.sh
Labels: type::bug, bug::normal

#11 have darwin_arm64 use kots_darwin_all release asset
  pkg/handlers/scripts.go
  pkg/handlers/scripts/install.sh
Labels: type::bug, bug::normal

#12 [release] add endpoint to fetch latest version
  main.go
  pkg/handlers/scripts.go
Labels: type::chore
